### ISSUE TITLE
`delete_stage_instance` and `leave_guild` operations require an empty json object as the body

### ISSUE THREAD

**Issue by danny-may** [discord/discord-api-spec#16]
The spec says that the `delete_stage_instance` operation requires an empty json object as its body, but in the docs website it doesnt have a request body 

https://discord.com/developers/docs/resources/stage-instance#delete-stage-instance
https://github.com/discord/discord-api-spec/blob/515b793b5d4e27c1049bbb9b445a2f1d4a07e4c1/specs/openapi.json#L8174-L8185

https://discord.com/developers/docs/resources/user#leave-guild
https://github.com/discord/discord-api-spec/blob/515b793b5d4e27c1049bbb9b445a2f1d4a07e4c1/specs/openapi.json#L3169-L3180

**Comment by yonilerner** [comment]
Ya this is an issue we've been aware of for a while. The docs are actually incorrect here, if you pass no request body we will fail the request. Our plan to solve this (no ETA):
- Never require a request body if it would be empty (runtime fix, not breaking because its more permissive)
- Then remove `requestBody` from OpenAPI spec in these situations

**Comment by danny-may** [comment]
Good to know which is correct, I was thinking id have to add in an edge case for these endpoints if the spec was incorrect

**Comment by mbialecka** [comment]
to clarify, docs are correct, we allow no request body on `DELETE`s, but there are some inconsistencies that we want to fix and eventually we will remove the empty `requestBody` from the spec

**Comment by mbialecka** [comment]
fixed the spec!
